set more off
set scheme burd    // match __main.do; produces clean-white calibration plots under graphs/inputs/

* set initial and final years
global year_start 1935
global year_stop 2100
global download_data 0		// 0 = load local .dta (default), 1 = re-download from dbnomics

cd "`c(pwd)'"
clear
do _prepare_programs.do					// this keeps routines that are repeated between dofiles

global f_results "" // paste here the path for your results output from Fortran if you want to compare model to data 
* currently the dofiles use our outputs


*** FROZEN FORTRAN INPUTS — not regenerated by any script.
* Kept under inputs_stata_code/frozen_fortran_inputs/ as source of truth.
* Copied to fortran_code/Data/ so they sit alongside the pipeline-generated
* Fortran inputs. See frozen_fortran_inputs/README.md for provenance.
foreach f in _data_Nn_US_1935_2100.txt _data_Nn_US_1935_init_old.txt _data_rho_1935.txt {
    capture copy "frozen_fortran_inputs/`f'" "../fortran_code/Data/`f'", replace
}

*** PROCESS DATA - FORTRAN INPUTS;
* PWT inputs;
global bsource "."
do depreciation/M01prepare_depr			
do tfp/M02prepare_gamma					
do labor_share/M03prepare_labor_share	
do ../sensitivity_stata_code/exog_rate/M04prepare_exog_rate		//this is just robustness, never frozen

* skill premium and high/low shares;
do skill_premium/H01prepare_skill_premium 
*college share
do skill_premium/D02_prepare_college 

* taxes and contributions;
do tax_rate/T01prepare_taxes
do social_security/T02prepare_contributions
do tax_rate/T03prepare_tax_lambda

* demography (pi_* Fortran inputs + Figure B.2 LE50year calibration plot);
* previously ran from outputs_stata_code/__main.do Appendix C — moved here
* because these produce Fortran inputs and belong in the input pipeline.
* D01 first because D03 reads D01's pi_tot_new.dta intermediate.
do demography/mortality/D01_life_tables
do demography/hetero_pi/D03_prepare_hetero_pi

* D01 writes _data_pi_cond_US_since1935.txt to demography/mortality/output/
* but Fortran (data.f90:380) reads it from fortran_code/Data/. Copy it
* across so the pipeline is self-contained.
capture copy "demography/mortality/output/_data_pi_cond_US_since1935.txt" ///
    "../fortran_code/Data/_data_pi_cond_US_since1935.txt", replace

capture erase bone.dta
capture erase bone1y.dta


